### ISSUE TITLE
Использование кавычек в CSS.

### ISSUE THREAD

**Issue by viktoriya-ch** [fullstack-development/front-end-best-practices#10]
В стандартах ничего не говорится о том, какие кавычки используются в CSS, одинарные или двойные, можно было бы добавить это в "Общие требования".

**Comment by Znack** [comment]
Хм, кстати да, добавляем @krashaen @in19farkt @sk1e @chmnkh?

**Comment by in19farkt** [comment]
Лишним не будет, особенно если в js такой пунктик есть

**Comment by krashaen** [comment]
> Хм, кстати да, добавляем @krashaen @in19farkt @sk1e @chmnkh?

 да, ща добалю

**Comment by krashaen** [comment]
#14 добавил
