### ISSUE TITLE
Структура папок.

### ISSUE THREAD

**Issue by viktoriya-ch** [fullstack-development/front-end-best-practices#11]
CSS/generalRequirements.md

> 4. Все правила должны быть разбиты на разные файлы по страницам и блокам, каждый файл не должен быть длинее чем 1000 строк;

Здесь можно было бы еще дополнить, что каждый блок должен лежать в своей папке, и папки блоков нельзя вкладывать друг в друга.

**Comment by krashaen** [comment]
#13 Дополнил
