### ISSUE TITLE
Имена css-классов.

### ISSUE THREAD

**Issue by viktoriya-ch** [fullstack-development/front-end-best-practices#12]
CSS/generalRequirements.md

> 12.Имена:
> 
> использовать lower-case-hyphenated (то есть не mySuperAwesomeElement и не my_super_awesome_element);
> имена должны отображать смысл, а не описание стилей ("loading" а не "big-yellow-spinny-thing");

Здесь еще можно добавить, что нельзя именовать классы с нумерацией: .icon-1, icon-2, icon-3... Мне кажется, такое часто встречается.

**Comment by krashaen** [comment]
Мне кажется, это:
> имена должны отображать смысл, а не описание стилей . 

как раз и говорит о том, что именовать как ..icon-1, icon-2, не стоит

**Comment by Znack** [comment]
ну кстати не факт, у тебя может быть реально первая, вторая и третья иконки, которые будут для разных пунктов, и тут можно назвать хоть так, и хоть по смыслу пунктов. То есть семантически иконку 💯 можно назвать icon-100, но скорее всего она бы означала в проекте что конкретно эта сотня характеризует и так лучше класс и давать :) Не `icon-100`, а `confidence-icon`, если это иконка символзирует 100% уверенность в какой-то позиции :)

**Comment by Znack** [comment]
@MorganaLF Я предлагаю тебе сразу Pull Request-ы не стесняться оформлять, там ты можешь предлагать сразу куда конкретно правило добавить и в какой формулировки, и мы прямо в контексте правок обсудим :)

**Comment by viktoriya-ch** [comment]
> Мне кажется, это:
> 
> > имена должны отображать смысл, а не описание стилей .
> 
> как раз и говорит о том, что именовать как ..icon-1, icon-2, не стоит

Да, пожалуй, это лишнее)

**Comment by viktoriya-ch** [comment]
> @MorganaLF Я предлагаю тебе сразу Pull Request-ы не стесняться оформлять, там ты можешь предлагать сразу куда конкретно правило добавить и в какой формулировки, и мы прямо в контексте правок обсудим :)

Хорошо)
