### ISSUE TITLE
Расписать как правильно писать коммиты и структурировать вносимые изменения

### ISSUE THREAD

**Issue by kinda-neat** [fullstack-development/front-end-best-practices#18]

**Comment by in19farkt** [comment]
Нужно изучить как это происходит в других командах, например вот ссылка на [стандарты команды atom-а](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages)

**Comment by in19farkt** [comment]
они эмоджи используют в коммитах))

**Comment by kinda-neat** [comment]
Да, здесь можно как минимум накидать источников и обсудить их

**Comment by kinda-neat** [comment]
https://chris.beams.io/posts/git-commit/

**Comment by in19farkt** [comment]
можно использовать связку commitizen + commitlint + standard-version.

**Comment by FanManutd** [comment]
Готово https://github.com/fullstack-development/front-end-best-practices/blob/master/Environment/conventional-commits.md
