### ISSUE TITLE
Соблюдать стандарты самим :)

### ISSUE THREAD

**Issue by kinda-neat** [fullstack-development/front-end-best-practices#26]
В первом пункте пишем про одно, а затем ниже сами его и нарушаем, надо исправить
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/jQuery.md

**Comment by Znack** [comment]
А что именно имеешь в виду? Давай детали что нарушалось и где :)

**Comment by kinda-neat** [comment]
Пункт
![image](https://user-images.githubusercontent.com/27883524/64959567-a332a500-d8bb-11e9-8783-9908f2b79259.png)
Примеры ниже 
![image](https://user-images.githubusercontent.com/27883524/64959587-a9c11c80-d8bb-11e9-910a-f039e55ddec3.png)
![image](https://user-images.githubusercontent.com/27883524/64959602-b0e82a80-d8bb-11e9-9b54-baaec600cc49.png)

**Comment by Znack** [comment]
@kinda-neat показал мастер класс как создавать PR :)
