### ISSUE TITLE
Орфография

### ISSUE THREAD

**Issue by arlgnv** [fullstack-development/front-end-best-practices#37]
Не знаю можно ли создавать issue по этому поводу, но когда изучаю best practices иногда встречаются такие ошибки
![image](https://user-images.githubusercontent.com/46949445/75525969-e889ff80-5a21-11ea-90c4-ff7e3cc3fa38.png)
Если нужно, буду сюда заносить неточности

**Comment by Znack** [comment]
Да по таким вещам либо ишью (но тогда надо максимально точно место указывать, чтобы мы быстро найти это смогли), либо сразу ПР открывать :)

**Comment by arlgnv** [comment]
Хорошо. [3 пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/react.md)
