### ISSUE TITLE
Wrong link in text

### ISSUE THREAD

**Issue by dimozavroid** [fullstack-development/front-end-best-practices#41]
[Frontend Best Practices - HTML](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/semantic.md)
Paragraph 3: **Константин Константинопольский**
Delete last symbol in link: https://tema.livejournal.com/1322108.html/

**Comment by Znack** [comment]
Thanks, fixed

**Comment by dimozavroid** [comment]
Good
