### ISSUE TITLE
Определение элемента footer

### ISSUE THREAD

**Issue by arlgnv** [fullstack-development/front-end-best-practices#43]
Мне кажется не совсем точно [указано п.8](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/semantic.md) определение для элемента. Footer может использоваться не только как подвал страницы, а также как нижний колонтитул section, article и aside. Думаю стоит дополнить, т.к. это достаточно важно для придания семантики документу

**Comment by Znack** [comment]
Согласен. Я думаю, тут можно сразу PR делать. Либо кстати можно вообще выпилить наши определения и вставить ссылку на более четкие уже еопубликованные в авторитетных источниках

**Comment by arlgnv** [comment]
> Согласен. Я думаю, тут можно сразу PR делать. Либо кстати можно вообще выпилить наши определения и вставить ссылку на более четкие уже еопубликованные в авторитетных источниках

Хорошо, займусь в ближайшие дни

**Comment by arlgnv** [comment]
@Znack А как ты смотришь на то, чтобы добавить пункт про использование button и a? Т.е. указать примеры, когда плохо использовать кнопку, а когда ссылку. Когда, к примеру, нужно делать элемент не просто span'ом, а button. Например у нас есть дропдаун, и у него есть стрелочка для его открытия, и что в этом случае она должна быть выполнена в виде button. Посмотрю статейки на эту тему, и придумаю может пару примеров, если нужно.

**Comment by Znack** [comment]
Я в целом только за :)

Но лучше, конечно, ещё и в итоге добавить сами ссылки в стандарты, чтобы это было описано более подробно в качественных источниках, а нам достаточно было сослаться
