### ISSUE TITLE
Обсуждение требования по установке одновременно ширины и высоты для тэга img.

### ISSUE THREAD

**Issue by AkhmadBabaev** [fullstack-development/front-end-best-practices#52]
![image](https://user-images.githubusercontent.com/51095975/92274430-e5525d80-eef5-11ea-8f0f-0ded3d15cf2f.png)

## Проблемы

1. Изображения установленные через `background` не индексируются.
2. Теряем семантику.
3. CSS cвойство [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) которое может дать изображению `img` поведение как при `background-size: cover` нуждается в установке ширины и высоты, что противоречит требованию.

## Варианты решения

1. Требование мы можем:
    1.1. Расширить, добавив информацию о том как быть в тех или иных ситуациях.
    1.2. Сократить, на пример - Избегайте действий нарушающие пропорции изображений.
    1.3. Убрать требование вовсе.

2. Вне зависимости от того что было выбрано в пункте 1, предлагаю:
    - Добавить в карту развития jun1/css: **Что делает свойство `object-fit`?**
    - Перенести с карты развития jun3/css вопрос **Когда стоит использовать тег img, а когда background-image?** в jun1/html или css, так как без знания когда и как подключать изображения знания про `object-fit` и прочие рекомендации будут менее эффективны.  Учитывая то, как часто перед нами стоит выбор `img` или `background-image` это надо знать уже на позиции jun1.

Результаты [Can I use](https://caniuse.com/#search=object-fit). Поддержка большинством передовых браузеров началась с 2013-14 годов.

**Comment by krashaen** [comment]
Согласен по большей степени с Ахмадом тут. Я бы оставил правило, изменив его под современные реалии. И явно бы указал про то что object-fit не поддерживается ie.
По поводу переноса вопроса тоже не против :)
@chmnkh призываю твое экспертное мнение)

**Comment by chmnkh** [comment]
> Добавить в карту развития jun1/css: Что делает свойство object-fit?

![image](https://user-images.githubusercontent.com/18498637/92593366-3504a080-f2cb-11ea-9acc-b112bbcd7666.png)

я бы свойства, находящиеся на на данной стадии стандартизации старался не добавлять карту, а здесь это свойство точно не маст хэв

**Comment by chmnkh** [comment]
Со 2 пунктом во всём согласен.
По поводу 1го, я предлагаю на самом деле вообще выпилить правило, потому что сама по себе проблема, что у картинки ВНЕЗАПНО нарушатся пропорции, довольно специфична, на мой взгляд, и нормальный фронтендер найдет как её решить, в том числе object-fit'ом, ну или если нельзя, background'ом. А сам по себе выбор между img и фоном должен, конечно, определяться не тем, фиксированный ли размер у картинки или нет.

**Comment by AkhmadBabaev** [comment]
> И явно бы указал про то что object-fit не поддерживается ie.

Согласен, об этом стоит упомянуть.

> По поводу 1го, я предлагаю на самом деле вообще выпилить правило, потому что сама по себе проблема, что у картинки ВНЕЗАПНО нарушатся пропорции, довольно специфична, на мой взгляд, и нормальный фронтендер найдет как её решить, в том числе object-fit'ом, ну или если нельзя, background'ом.

Я сталкивался с тем когда разработчик намеренно нарушает пропорции изображений, такие решения принимались новичками по незнанию. Хорошие практики как раз должны помочь стать лучше. 

Да, мы вполне можем описать варианты решения, но опасаюсь того что наше решение может оказаться не пригодным для какиx-то иных проявлений текущей проблемы, поэтому моим фаворитом является пункт 1.2 - сокращение требования до основной мысли, пункт 2 не даст инструкцию на все случаи жизни, но даст необходимую базу. 

Что скажите ? @krashaen, @chmnkh, @Znack.

**Comment by chmnkh** [comment]
> Я сталкивался с тем когда разработчик намеренно нарушает пропорции изображений.

Можно пример? Не совсем понял, как это так)

**Comment by Znack** [comment]
> Я сталкивался с тем когда разработчик намеренно нарушает пропорции изображений.
> Можно пример? Не совсем понял, как это так)

Я так понял, тут про случай, когда новичок сверстал и поставил фиксированные размеры, забив на пропорции, потому что ему тупо лень было нормально сделать :) Это же стандарты, которые в том числе для новичков, чтобы основные косяки предостеречь, так что тут такое правило больше помогает, чем мешает, как по мне

**Comment by AkhmadBabaev** [comment]
> Можно пример? Не совсем понял, как это так)

Такое случается когда у нас есть блок с фиксированными размерами который получает различные изображения. 
Как образец, блоки изображений с [wallpaperscraft](https://wallpaperscraft.com/all/page9), хотя изображения тут подаются уже под стать размерам блока но такое не на всех сайтах. Разработчик может задать ширину и высоту, чтобы изображения различных размеров вписывались в блок, не осознавая важности пропорций, в добавок на этапе разработки он скорее всего получит от дизайнера изображения с размерами близким к размеру блока, где искажение пропорций не будет заметно.

**Comment by chmnkh** [comment]
> Разработчик может задать ширину и высоту, чтобы изображения различных размеров вписывались в блок, не осознавая важности пропорций

> Я так понял, тут про случай, когда новичок сверстал и поставил фиксированные размеры, забив на пропорции, потому что ему тупо лень было нормально сделать

Ну короче, я так понимаю, вы оба говорите про кейс, что разработчик не догоняет, что пропорции, внезапно, важны. Для меня соответствие пропорций - это очевидное требование, которое следует тупо из здравого смысла. Если разработчик этого не понимает, то это прямо печаль какая-то. В общем, я не считаю, что такие вещи нужно здесь фиксировать, но спорить и настаивать тоже не буду.

Отдельно про "забивает" Серегино выскажусь: ну это вообще уже финиш, если чувак забивает и как попало свою работу делает, то с таким чуваком не "требованиями на гитхабе" бороться надо, как по мне.

**Comment by Znack** [comment]
Мне кажется, ты с высоты опыта судишь и мало с совсем начинающими в последнее время работал :)
Иногда и умный и ответственный человек может не увидеть важность этих пропорций, для меня это не является метрикой того, что тут однозначно "печаль". Стандарты же как раз позволяют один раз собрать все такие возможные костыли, направить в нужную сторону. И вот дальше уже можно считать значимым наблюдением соблюдаются ли стандарты, потому что ошибиться один раз это норм, но несколько раз да еще и имея под рукой такие правила — вот для меня тут "печаль" начинается :)

**Comment by chmnkh** [comment]
Ну это не про опыт вообще, на мой взгляд. Но спорить не хочу)

**Comment by AkhmadBabaev** [comment]
На текущий момент мы вроде как единогласны по пункту 2, осталось определиться с первым пунктом. 
Думаю нам стоит указать на то, что нарушать пропорции это плохо. Если считаете, что было бы не плохо описать решения данной проблемы то стоит попробовать и на этапе работы над PR, в зависимости от результата принять решение стоит ли нам это делать )

Ваше мнение ? - @krashaen, @chmnkh, @Znack.

**Comment by chmnkh** [comment]
У меня мнение не поменялось, я считаю, что "не нарушать пропорции" - это здравый смысл. На мой взгляд, нарушение пропорций изображений - это вещь, которая бьется в глаза сразу же, интерфейс с такими изображениями выглядит плохо и поломанно.

А я не думаю, что желание делать приятные, хорошо работающие и выглядящие интерфейсы, или перефекционизм какой-то - это то, что с опытом придет, или что для этого нужно каким-то знанием овладеть. А нарушение пропорций изображения - это про это как раз.

Поэтому я не считаю, что стоит как-либо вообще момент с пропорциями упоминать.

**Comment by Znack** [comment]
Ну я тут за то, что это хоть и подразумевается как разумный навык, но всё же нормально в стандартах оставить, чтобы все стажеры себя могли перепроверить. Тут же у нас это в первую очередь удобный чеклист для новичков, чтобы они могли системно по всем популярным граблям пройтись. Ну и указание этого пункта в одну строчку не выглядит чем-то сильно усложняющим :) В итоге польза, хоть и призрачная есть, а проблем от этого пункта нет.
Ну и я сторонник, что если можно не надеяться в этом вопросе на то, что искажение будет биться в глаза и что всем здравым джуниорам будет всё очевидно :)

Давайте еще мнение @in19farkt послушаем и принимаем решение

**Comment by in19farkt** [comment]
Во многом согласен с Лёхой, есть ощущение что раздули из мухи слона))

Моё мнение такое:
- умение различить `img` и `background-image` - **важно**, т.к. в целом чтобы осознать разницу требуется больше усилий, и джуну закосячившему на проекте придется объяснять почему так а не по другому, а это потенциальная трата времени и джуна и тимлида
- умение не косячить пропорции - **вообще похер**, визуально заметно на ревью/проверке ПРа, ничего объяснять не нужно, достаточно просто сказать "эй, бро, у тебя тут пропорции съехали, погугли про object-fit (или background-size: cover)", всё гуглится (а может вспоминается) и исправляется за 10-20 минут

Но в целом я не против оставить небольшую заметку на счет пропорций, ничего плохого в этом не вижу.

**Comment by Znack** [comment]
Ну да, давайте тогда явно напишем, что не надо путать когда юзать `img` и когда `background-image`. Если при этом в формулировках будет упоминание про косяки с пропорциями, то пусть будет, а если нет, то ок :)

@AkhmadBabaev вроде пришли к решению наконец :)
