### ISSUE TITLE
Изменить формулировку пункта 4.4 в разделе CSS

### ISSUE THREAD

**Issue by dywork** [fullstack-development/front-end-best-practices#58]
![Снимок](https://user-images.githubusercontent.com/17548109/95045291-142d4080-06fb-11eb-8561-6b01d93e490a.PNG)
[https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.4](url)

Предлагаю: 
1. Удалить явно лишнее быть.
2. Удалить тавтологию с должен.
3. Изменить окончание в слове самодостаточен на ным (быть каким?).

Как итог: "Каждый компонент должен иметь только явные зависимости, быть самодостаточным."

**Comment by Znack** [comment]
Вмержили 👍
