### ISSUE TITLE
Недействительная ссылка на перевод Flexbugs

### ISSUE THREAD

**Issue by danfimov** [fullstack-development/front-end-best-practices#65]
В конце раздела о CSS:

    Подробнее об этом и других багах, возникающих при работе с флексами, можно прочитать на Flexbugs, перевод 
    материала на русский здесь.

Ссылка на русскоязычный материал не работает (это просто свободный домен на данный момент). Я погуглил свежие материалы на эту тему, но ничего раньше 2015 года не нашел – [ссылка](https://css-live.ru/articles/brauzernye-bagi-flexbox.html) на материал с css-live.

Можно приложить ссылку на вышеупомянутый материал, либо вовсе убрать текст о русскоязычной версии.

**Comment by nelliza** [comment]
Спасибо за вклад в наши стандарты )
