### ISSUE TITLE
Использование W3C Markup Validation Service

### ISSUE THREAD

**Issue by NZMinusDev** [fullstack-development/front-end-best-practices#67]
Предлагаю вынести некоторые пункты HTML стандартов в один: "Прогонять страницы через [валидатор](https://validator.w3.org/)".

### Решаемые проблемы:
- уплотнится структура стандартов, что упростит запоминание;
- процесс поиска многих ошибок будет частично автоматизирован;
- валидатор также сообщает и о ошибках, не отображенных в текущих стандартах: `<input>` внутри `<button>` или `<a>`.

### Пункты стандартов, которые проверяет валидатор:
- [не вставлять блочные элементы внутрь инлайновых](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#1.4);
- [начинаем новый .html файл с `<!DOCTYPE html>`](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.3);
- [самозакрывающиеся теги](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.8);
- [изображения должны содержать `alt`](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.13);
- [не допускать вложенные формы `<form>`](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.20).

**P.S.**: [расширение](https://chrispederick.com/work/web-developer/) позволяет прогонять страницы локально.

**Comment by arlgnv** [comment]
Ну я тут только за, даже нечего добавить :)

**Comment by NZMinusDev** [comment]
Единственно, не знаю насколько строгим должен быть стандарт: например, считать ли warning-и по отсутствую заголовков у `<section>`  как критерий, что проект не соответствует стандарту.

**Comment by arlgnv** [comment]
Ну мне кажется, главное, чтобы не было ошибок, а предупреждения это уже чисто исходя из проекта смотреть
